version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "1424:1433"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./models/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
