services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./api
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    volumes:
      - ./api:/app
      - /app/node_modules
    env_file:
      - ./.env
    command: sh -c "npm install --include=dev && npm run dev"

  frontend:
    build: ./frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm ci || npm install && npm run dev -- --host"

volumes:
  pgdata: